### ISSUE TITLE
Popup for add cooments

### ISSUE THREAD

**Issue by israelperezglez** [47deg/scala-days-ios#55]
We will design a popup for add comments about differents talks

**Comment by israelperezglez** [comment]
@jdesiloniz I attach the screens and the assets

![vote](https://cloud.githubusercontent.com/assets/646886/15604883/f47f141e-2402-11e6-9e0b-bc0300dacc5d.png)

[assets.zip](https://github.com/47deg/scala-days-ios/files/286234/assets.zip)

**Comment by MaureenElsberry** [comment]
Hi @israelperezglez just a little edit for the screen text:    Leave a comment on your opinion of this talk to help out the speaker.

If it's not too late to adjust that.

Thanks!

**Comment by jorgegalindocruces** [comment]
It is not too late. Thanks @MaureenElsberry, good catch!

**Comment by jdesiloniz** [comment]
@MaureenElsberry thanks! already changed it on the iOS version!
