### ISSUE TITLE
App crashes on iPhone when scanning contact

### ISSUE THREAD

**Issue by alejandrolujan** [47deg/scala-days-ios#61]
I've tried scanning a couple different QR codes, and the app crashes consistently. I have not been able to scan a single code successfully.

I'm on an iPhone 6, but I also observed this on another attendee using a newer iPhone.

This happened on April 19 around noon CDT.

**Comment by raulraja** [comment]
@alejandrolujan Thanks for reporting this, our team is working on a fix and will try to get it up ASAP.
