### ISSUE TITLE
Missing speaker descriptions and incorrect portraits

### ISSUE THREAD

**Issue by alejandrolujan** [47deg/scala-days-ios#63]
While examining the speaker list for ScalaDays Copenhagen, I noticed a few are missing a description, and/or their names don't match the photo shown.

Not sure if this is one issue or two...

See the following screenshots:

1. Emily's photo is incorrect, and missing description:

![img_4364](https://cloud.githubusercontent.com/assets/723599/25345545/6462d730-28e3-11e7-8283-d9765048e7e1.PNG)

2. Haoyi's photo is correct, but missing description:

![img_4365](https://cloud.githubusercontent.com/assets/723599/25345548/6467c29a-28e3-11e7-9612-d9ffa86a0fd7.PNG)

3. Imran's photo is incorrect, but description seems fine:

![img_4366](https://cloud.githubusercontent.com/assets/723599/25345546/6464e4bc-28e3-11e7-8346-5f06c10d8357.PNG)

4. And a few other cases of the above:

![img_4367](https://cloud.githubusercontent.com/assets/723599/25345544/645f2c3e-28e3-11e7-884b-903d6adb72bc.PNG)
![img_4368](https://cloud.githubusercontent.com/assets/723599/25345549/646b8902-28e3-11e7-9ff5-6869f29a6a79.PNG)
![img_4369](https://cloud.githubusercontent.com/assets/723599/25345547/6464f45c-28e3-11e7-89dc-db337aa5cda1.PNG)
![img_4370](https://cloud.githubusercontent.com/assets/723599/25345550/647327d4-28e3-11e7-8e69-1e1397e3d05b.PNG)
![img_4371](https://cloud.githubusercontent.com/assets/723599/25345551/6473e124-28e3-11e7-898a-4871a2c6a597.PNG)
![img_4372](https://cloud.githubusercontent.com/assets/723599/25345552/64742ed6-28e3-11e7-990c-01180304fc95.PNG)

Hope this helps...

**Comment by MaureenElsberry** [comment]
Hi, @alejandrolujan - For the missing descriptions it's because they pull from the Scala Days website and they don't have their bios included on the site. But it does appear that some of these names are no longer speaking possibly.... we'll look into this. Thanks.

**Comment by alejandrolujan** [comment]
Sure, happy to test this again when a fix is pushed.

I'm on iOS so unfortunately have to wait for the publishing process to complete.
