### ISSUE TITLE
App doesn't store selected event place

### ISSUE THREAD

**Issue by mr-git** [47deg/scala-days-ios#64]
If one chooses Copenhagen event, then after app restart Chicago is selected by default.
Would be nice if app would remember the event I chose.

**Comment by anamariamv** [comment]
@mr-git Thanks for reporting this improvement. Please feel free to contribute by creating a pull request to add this functionality.

**Comment by pboschmann** [comment]
This issue, although quite aged, is still relevant — I reproduced it with the code in current master.
I could fix it this weekend, if you like (shouldn't be a big deal, I've already checked out the repo and the code compiles)…

**Comment by miguelangel-dev** [comment]
Ey @mr-git  and @pboschmann  thanks so much for your interest in that issue -- I have read this some days ago and today I launched the PR adding this feature. [Here the PR](https://github.com/47deg/scala-days-ios/pull/83)

In the next ScalaDays release, you will find it. Thanks for the patient ^^
