### ISSUE TITLE
When vote sending fails, app forgets my input

### ISSUE THREAD

**Issue by mr-git** [47deg/scala-days-ios#65]
Happens on bad wi-fi. One enters rating, enters comment, tries to send, network fails, app closes dialog. Upon opening the dialog again, my input is lost.
It would be nice, if app would remember my inputs, at least in case the sending failed.

**Comment by anamariamv** [comment]
@mr-git Thanks for reporting this improvement. Please feel free to contribute by creating a pull request to add this functionality.

**Comment by miguelangel-dev** [comment]
I think it was fixed last year (2019), I will close it for now
