### ISSUE TITLE
Missing splash screen for iPhone X

### ISSUE THREAD

**Issue by juancazalla** [47deg/scala-days-ios#67]
As part of the iPhone X support, we need a splash screen for this model. 
The size is 1124 x 2436

**Comment by israelperezglez** [comment]
@juancazalla I attach the splash for iPhone X 

![splash](https://user-images.githubusercontent.com/646886/39174045-d6ece98e-47a6-11e8-9b1e-10d5f3d7466b.png)

**Comment by juancazalla** [comment]
Thanks!
