### ISSUE TITLE
Link to anonymous feedback

### ISSUE THREAD

**Issue by rafaparadela** [47deg/scala-days-ios#78]
This issue is linked to this one https://github.com/47deg/scala-days-backend/issues/102

In the backend, we added some changes to include a link at the `info` level. As you can see, every conference now includes a required link called `feedback`:

```javascript
"info": {
	"id": 20201,
	"name": "scala-days-lausanne-2020",
        ...
         "feedback": "{Any google form link}"
}
```

The idea is to show a fixed button in the Code of Conduct screen to redirect the user to a form via the default browser.

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-27 at 15 58 52](https://user-images.githubusercontent.com/315070/75499176-1ae22100-597e-11ea-9c41-24bd7900acef.png)

**Comment by miguelangel-dev** [comment]
Done in PR https://github.com/47deg/scala-days-ios/pull/77
